///
/// Generated by bookproto
/// Do't modify this file directly, new partial class file instead.
///
using System;
using System.IO;
using System.Collections.Generic;
using bookrpg.net;
using bookrpg.net.protobuf;
using bookrpg.utils;

	public partial class Login_s2c : Message 
    {
		private uint _retCode;
		public  uint retCode 
		{
			get{return _retCode;}
			set{_retCode = value;_hasRetCode=true;}
		}

        private bool _hasRetCode = false;
        public  bool hasRetCode {get{return _hasRetCode;}}
		public  void clearRetCode() {_hasRetCode=false;}


		public override void Deserialize(ByteArray stream)
		{
			base.Deserialize(stream);
			
            int retCodeCount = 0;

            while (stream.bytesAvailable > 0)
            {
                var tag = ReadUtils.ReadTag(stream);
                switch (tag.number)
                {
                	case 0:
                        throw new ProtobufException("Invalid field id: 0, wrong stream");
                    case 1:
						this.retCode = ReadUtils.Read_TYPE_UINT32(stream);
						retCodeCount++;
                        break;
					default:
                        ReadUtils.Skip(stream, tag.wireType);
                        break;
                }
            }

            if (retCodeCount == 0) {
                throw new ProtobufException("Required field retCode not readed");
            }
		}

		public override ByteArray Serialize(ByteArray stream=null, bool skipHead = false)
		{
			stream = base.Serialize(stream, skipHead);

			if (this.hasRetCode ) {
                WriteUtils.WriteTag(stream, WireType.Varint, 1);
                WriteUtils.Write_TYPE_UINT32(stream, this.retCode); 
			} else {
                throw new ProtobufException("Required field retCode not set");
            }


			return stream;
		}

    
    }
