<?php 
/**
 * Generated by bookproto
 * Do't modify this file directly, new inherited class file instead.
 */

namespace  
{
	class Login_s2c extends \bookrpg\route\impl\DefaultMessage 
    {
    	/* @var array Field descriptors */
	    protected static $fields = array(
	        1 => array(
	            'name' => 'retCode',
	            'required' => true,
	            'type' => 5,
	        ),
	    );

	    /**
	     * Constructs new message container and clears its internal state
	     *
	     * @return null
	     */
	    public function __construct()
	    {
	        $this->reset();
	    }

	    /**
	     * Clears message values and sets default ones
	     *
	     * @return null
	     */
	    public function reset()
	    {
	        $this->values[1] = null;
	    }

	    /**
	     * Returns field descriptors
	     *
	     * @return array
	     */
	    public function fields()
	    {
	        return self::$fields;
	    }

		public function getRetCode()
		{
			return $this->get(1);
		}

		public function setRetCode($value)
		{
			return $this->set(1, $value);
		}
    }

}


