<?php 
/**
 * Generated by bookproto
 * Do't modify this file directly, new inherited class file instead.
 */

namespace  
{
	class Login_c2s extends \bookrpg\route\impl\DefaultMessage 
    {
    	/* @var array Field descriptors */
	    protected static $fields = array(
	        1 => array(
	            'name' => 'username',
	            'required' => true,
	            'type' => 7,
	        ),
	        2 => array(
	            'name' => 'password',
	            'required' => true,
	            'type' => 7,
	        ),
	    );

	    /**
	     * Constructs new message container and clears its internal state
	     *
	     * @return null
	     */
	    public function __construct()
	    {
	        $this->reset();
	    }

	    /**
	     * Clears message values and sets default ones
	     *
	     * @return null
	     */
	    public function reset()
	    {
	        $this->values[1] = null;
	        $this->values[2] = null;
	    }

	    /**
	     * Returns field descriptors
	     *
	     * @return array
	     */
	    public function fields()
	    {
	        return self::$fields;
	    }

		public function getUsername()
		{
			return $this->get(1);
		}

		public function setUsername($value)
		{
			return $this->set(1, $value);
		}
		public function getPassword()
		{
			return $this->get(2);
		}

		public function setPassword($value)
		{
			return $this->set(2, $value);
		}
    }

}


