#!/usr/bin/php
<?php
require 'bookproto/bookproto/Bookproto.php';

$prjroot = dirname(__DIR__) . '/';

$params = array(
    //frequently used
    'inputPath' => "", //directory or name*.ext* file
    'outputPath' => "protos", //directory
    'codeType' => "C#",

    //barely used
    'prefix' => "",
    'parentClass' => "",
    'templateDir' => "", //the codeType's template directory
    'commentSymbol' => "#", //like #xxx.proto file will be ignored
    'onlySimpleName' => true, //file name contains letter, number or underline only
    'genPackageDir' => true, //auto generate package directory
);

$params['inputPath'] = $prjroot . 'proto/*.proto';
$params['outputPath'] = $prjroot . 'server/GameServer/proto/';
$params['codeType'] = 'PHP';
parseProtos($params);

