///
/// Generated by bookproto
/// Do't modify this file directly
///
namespace bookrpg.test 
{
    public enum Enum1 
    {
    	a = 1,
    	b = 2,
    	c = 3,
	}

    public enum Enum2 
    {
    	a = 1,
    	b = 2,
    	c = 3,
	}

}